Update pipeline

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -66,9 +66,16 @@ jobs:
         node-version: '20'  
         cache: 'npm'
 
+    - name: Check for dependency lock file
+      run: |
+        if [ ! -f ./frontend/package-lock.json ] && [ ! -f ./frontend/yarn.lock ]; then
+          echo "Error: No dependency lock file found (package-lock.json or yarn.lock)."
+          exit 1
+        fi
+
     - name: Install frontend dependencies
       working-directory: ./frontend
-      run: ls -la && pwd && npm install
+      run: npm install
 
     - name: Run Angular tests
       working-directory: ./frontend
